# CI for openseaChest through Travis CI
language: c

branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - os: linux
    sudo: false
    compiler: clang
    dist: xenial
    before_script: cd Make/gcc
    script: make release
  - os: linux
    sudo: false
    compiler: gcc
    dist: xenial
    before_script: cd Make/gcc
    script: make release
    deploy:
      provider: releases
      file_glob: true
      skip_cleanup: true
      file: openseachest_exes/*
      api_key:
        secure: wkNKnZEv3JQ8eyNWQDKt6eH4becLyqkJmZ4EVBfGoTQ9OHj4sSb2eRR9E1l/u1HFHzA0DFeEKSb25BcmIt0/1I1voKCGFTqLXUTDK6H5ehbkke6hWXy7uSjjtbxLbTGGhrQjDwqdbpOXGYI92kGJbZh1oifsL4ARcP7GaKNJhGUkbBpArsbWFdKB8Z4WUINKwVJQs5Ts0zc1dFTvN3cvcPqzzVL4jlohNkCcykbwRc8ASmucqwGuK3FiTV/NQsZB7KkW5ZicglEzj20fn/OQF7Rg4atFJLdlKCPtmU4eSqDxHOwWbiuHFfoOihu+CkW+qiSy0jJqMKJ1uhl26uK1o1tUYrOOpuA7OGcLv4oKH/sozsfwWzCYDhoyjljlG81CtJ4cSW4wGkc9lz+VwvNZGDFEHeG3XL3Oa/KCcyX+1OFNwgyVFnaPucP7Kn62OCd10VVw+Hx3K2YBGbGmNkzI2deQBzxMeVVmvd+PeF0KKf5JrgH57I/z815UtmMD5m0hGjkL+ynCUlkRbWYCbVQ0XAqkED7bA6KBW+5EIIJNOlOW/M8X0VC9Vhy0+jtiOOmU+n9g50wjJaAJhXop/njPSv9KA65mUoLw1VCdInIIsd1AVpcryXI/Qb3N1AXbcBZHlPoD9npNB+W4yQqYWpIMCE8RgkvPTrT3LDlX5we1og8=
      on:
        repo: ahmadjee/openSeaChest
        tags: true
  #- os: windows
  #  env:
  #  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
  #  #- MSDEPLOY_PATH="c:\Users\travis\build\Seagate\openSeaChest\Make\VS.2017\x64\Static-Release\*"
  #  before_script: 
  #  - cd "Make\VS.2017"
  #  - pwd
  #  script:
  #  - export PATH=$MSBUILD_PATH:$PATH
  #  - echo $PATH
  #  - MSBuild.exe //p:Configuration=Static-Release //p:Platform=x64
  #  - echo %errorlevel%

