language: c
branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - os: linux
    sudo: false
    compiler: clang
    dist: xenial
    before_script: cd Make/gcc
    script: make release
  - os: linux
    sudo: false
    compiler: gcc
    dist: xenial
    before_script: cd Make/gcc
    script: make release
    deploy:
      provider: releases
      api_key:
        secure: bEQ9WuxaMMqRbDGn2W9SERdwOOHahW3JSDgxiOjH+LSNls2PgKaIF1CmFA1BxgJlC8kFB4OxDIvUN3i5O/7zmocHRO93Decy8rNGQZCuEY8043vgZwy/98TLXFC0EKKCpVPgc9h8PXkMZ24PCILcaGedJr10rCXqVzNOwYMEouw9plMuYH2HciSrd7imztjdOCItuayevhCV9+YWwmYwkqfgvkqLVVZUtMrtTbtmHIRX4+R4M0ZTuCgDeiZu8wuwibM4hkVlNBo+sq3DabeQnnnG22+a9eLYdZEgJ4VqOIYCYaAWNa2yiR+X6unRYMClDtp1Ne8vZeudMz3e/i+7JSs2KO+9XGtGhEAtvJ+Ghjhp6cgKsb34DBwE9lzzqQyT/xqQ0+MP+oznuzp6hOP787ZfVuxifAw/3OgMRg1am4IddI5JhNHZwNnlqm/XGdfBqy36LHXmVBd1DycT24bzAX28IoewM5en/Os8D+hzHoiCPrPdyYwCNoH8jZ32wwgJTuHQ0xsgR/tj94yyEKKFzygMRoQqfMWMbWrBl6nRhf166ZSqtC1V01KvBISxUcMJVgzh+oL63gRu7VLix9yNzlFO1sKuOumR+jxEIP8mZ9lxPqS+UQUMCYMqUhVou8ER0gABVlByNbpEL08h67uZh25iJYKGxWqdVlh5orIH0FI=
      file_glob: true
      file: openseachest_exes/*
      skip_cleanup: true
      on:
        repo: ahmadjee/openSeaChest
        tag: true
